### ISSUE TITLE
 Checklist for The Final Submission of our Design Prototype

### ISSUE THREAD

**Issue by ZainabAlnaboud** [deco3500/DJMZ#16]
This issue just to check that everything are included for the final submission of our design prototype.

Our submission should include:
- [x] Our research
- [x] Our data that we gather from the survey
- [x] Our wireframes and an explanation for each
- [x] Link for our interactive prototype
- [x] Documentation of the design process and a Summary for each stand-up

The documentation outline**:
- [x] Promotional Material
- [x] Link to the prototype
- [x] Summary
- [x] Process
- [x] Include a list of who did what in the project

*\* For more details please refer to the format section on the task-sheet

**Comment by jinshin1013** [comment]
how are we going about this? Please update!

**Comment by ZainabAlnaboud** [comment]
@SimplifyWeb all good!
